/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FormFeedback: typeof import('./src/components/FormFeedback.vue')['default']
    FormSurvey: typeof import('./src/components/FormSurvey.vue')['default']
    FormUploadImage: typeof import('./src/components/FormUploadImage.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconEpClose: typeof import('~icons/ep/close')['default']
    IconEpPlus: typeof import('~icons/ep/plus')['default']
    IconEpWarningFilled: typeof import('~icons/ep/warning-filled')['default']
    IconEpZoomIn: typeof import('~icons/ep/zoom-in')['default']
    IconMdiTrash: typeof import('~icons/mdi/trash')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    UploadContainer: typeof import('./src/components/UploadContainer.vue')['default']
    UploadImageZone: typeof import('./src/components/UploadImageZone.vue')['default']
  }
}
